"""Core ports — interface contracts for the hexagonal architecture."""

from loopengine.core.ports.inbound.orchestrator_port import (
    CheckItem,
    DoctorResult,
    ImproveResult,
    InitResult,
    OrchestratorPort,
    PlanResult,
    ReviewResult,
    RunResult,
)
from loopengine.core.ports.inbound.workflow_command import (
    CancelWorkflowCommand,
    CreateWorkflowCommand,
    StartWorkflowCommand,
    WorkflowCommandPort,
)
from loopengine.core.ports.inbound.workflow_query import WorkflowQueryPort, WorkflowSummary
from loopengine.core.ports.outbound import (
    AgentResponse,
    BaseAgent,
    ExecutionResult,
    Executor,
    Logger,
    MemoryStore,
    MetricsCollector,
    Planner,
    PlanPhase,
    PlanStep,
    ReflectionDecision,
    ReflectionEngine,
    ReflectionResult,
    ReviewComment,
    Reviewer,
    ReviewVerdict,
    Severity,
    ValidationIssue,
    ValidationResult,
    Validator,
)

__all__ = [
    # Outbound
    "AgentResponse",
    "BaseAgent",
    "CancelWorkflowCommand",
    # Inbound
    "CheckItem",
    "CreateWorkflowCommand",
    "DoctorResult",
    "ExecutionResult",
    "Executor",
    "ImproveResult",
    "InitResult",
    "Logger",
    "MemoryStore",
    "MetricsCollector",
    "OrchestratorPort",
    "PlanPhase",
    "PlanResult",
    "PlanStep",
    "Planner",
    "ReflectionDecision",
    "ReflectionEngine",
    "ReflectionResult",
    "ReviewComment",
    "ReviewResult",
    "ReviewVerdict",
    "Reviewer",
    "RunResult",
    "Severity",
    "StartWorkflowCommand",
    "ValidationIssue",
    "ValidationResult",
    "Validator",
    "WorkflowCommandPort",
    "WorkflowQueryPort",
    "WorkflowSummary",
]
